language: node_js
node_js:
  - "12"

services: mongodb

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
    - stage: deploy
      script:
        - echo "Ready to deploy..."
      deploy:
        provider: heroku
        app: splitmate-api
        api_key: ${HEROKU_KEY}

stages:
  - compile
  - test
  - deploy