language: node_js
node_js:
  - "12"

branches:
  only:
  - master

services: mongodb

addons:
  sonarcloud:
    organization: "trackerforce"
    token: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile and test
      script:
        - npm install
        - npm test
        - sonar-scanner
    - stage: deploy
      if: type NOT IN (pull_request)
      script:
        - echo "Ready to deploy..."
      deploy:
        provider: heroku
        app: splitmate-api
        api_key: ${HEROKU_KEY}

stages:
  - compile and test
  - deploy to staging