language: node_js
node_js:
  - "12"

services: mongodb

addons:
  sonarcloud:
    organization: "trackerforce"
    token: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
        - sonar-scanner
    - stage: deploy
      if: branch = master
      script:
        - echo "Ready to deploy..."
      deploy:
        provider: heroku
        app: splitmate-api
        api_key: ${HEROKU_KEY}

stages:
  - compile
  - test
  - deploy